library(geozoo)
testDoct = newXMLDoc()
top = newXMLNode("AEM3DOutput", doc=testDoct)
time = newXMLNode("GlobalTime", parent = top)
newXMLNode("interval", "12", parent = time)
newXMLNode("globalVariable", "TEMPERATURE", parent=top)
newXMLNode("globalVariable", "U_VELOCITY", parent=top)
newXMLNode("globalVariable", "V_VELOCITY", parent=top)
newXMLNode("globalVariable", "DO", parent=top)
newXMLNode("globalVariable", "FDIAT", parent=top)
newXMLNode("globalVariable", "NODUL", parent=top)
newXMLNode("globalVariable", "CYANO", parent=top)
newXMLNode("globalVariable", "CYANO_rho", parent=top)
newXMLNode("globalVariable", "CYANO_temperature_growth", parent=top)
newXMLNode("globalVariable", "CYANO_growth_rate", parent=top)
newXMLNode("globalVariable", "CYANO_respiration_rate", parent=top)
newXMLNode("globalVariable", "CYANO_excretion_rate", parent=top)
newXMLNode("globalVariable", "CYANO_tot_grazed_rate", parent=top)
newXMLNode("globalVariable", "TCHLA", parent=top)
newXMLNode("globalVariable", "NO3", parent=top)
newXMLNode("globalVariable", "NH4", parent=top)
newXMLNode("globalVariable", "PO4", parent=top)
newXMLNode("globalVariable", "TN", parent=top)
newXMLNode("globalVariable", "TP", parent=top)
newXMLNode("globalVariable", "SiO2", parent=top)
newXMLNode("globalVariable", "SSOL1", parent=top)
newXMLNode("globalVariable", "SSOL2", parent=top)
newXMLNode("globalVariable", "PAR", parent=top)
newXMLNode("globalVariable", "PAR_EXTINCTION", parent=top)
newXMLNode("globalVariable", "PATH_VIABLE", parent=top)
newXMLNode("globalVariable", "PATH_INACTIVE", parent=top)
newXMLNode("globalVariable", "PATH_VIABLE_SED", parent=top)
newXMLNode("globalVariable", "PATH_INACTIVE_SED", parent=top)
newXMLNode("globalVariable", "SEAGRASS", parent=top)
profile = newXMLNode("Profile", parent=top)
newXMLNode("filename", "fhlprofile.nc", parent=profile)
newXMLNode("location", "51,44", parent=profile)
newXMLNode("location", "25,40", parent=profile)
newXMLNode("location", "41,31", parent=profile)
newXMLNode("location", "74,46", parent=profile)
newXMLNode("location", "24,47", parent=profile)
newXMLNode("location", "14,23", parent=profile)
newXMLNode("location", "58,13", parent=profile)
newXMLNode("location", "50,49", parent=profile)
curtain = newXMLNode("Curtain", parent=top)
newXMLNode("filename", "curtainMain.nc", parent=curtain)
newXMLNode("location", ":,35", parent=curtain)
curtain2 = newXMLNode("Curtain", parent=top)
newXMLNode("filename", "curtainMain2.nc", parent=curtain2)
newXMLNode("location", "50,:", parent=curtain2)
sheet = newXMLNode("Sheet", parent=top)
newXMLNode("filename", "surfsheet.nc", parent=sheet)
newXMLNode("type", "SURFACE", parent=sheet)
newXMLNode("value", "1.0", parent=sheet)
sheet2 = newXMLNode("Sheet", parent=top)
newXMLNode("filename", "sheet15m.nc", parent=sheet2)
newXMLNode("type", "SURFACE", parent=sheet2)
newXMLNode("value", "15.0", parent=sheet2)
saveXML(testDoct, file="C:/Users/daniel.wilkerson/Desktop/Working R Directory/Data/modelData/datablock/datablock.xml")